import { TypedSchema, typed, union } from '@speakeasy-api/tonic';

import type { InlineTypeUnion10 } from './InlineTypeUnion10';
import { InlineTypeUnion10Schema } from './InlineTypeUnion10';
import type { InlineTypeUnion11 } from './InlineTypeUnion11';
import { InlineTypeUnion11Schema } from './InlineTypeUnion11';
import type { InlineTypeUnion12 } from './InlineTypeUnion12';
import { InlineTypeUnion12Schema } from './InlineTypeUnion12';
import type { InlineTypeUnion13 } from './InlineTypeUnion13';
import { InlineTypeUnion13Schema } from './InlineTypeUnion13';
import type { InlineTypeUnion14 } from './InlineTypeUnion14';
import { InlineTypeUnion14Schema } from './InlineTypeUnion14';
import type { InlineTypeUnion4 } from './InlineTypeUnion4';
import { InlineTypeUnion4Schema } from './InlineTypeUnion4';
import type { InlineTypeUnion5 } from './InlineTypeUnion5';
import { InlineTypeUnion5Schema } from './InlineTypeUnion5';
import type { InlineTypeUnion6 } from './InlineTypeUnion6';
import { InlineTypeUnion6Schema } from './InlineTypeUnion6';
import type { InlineTypeUnion7 } from './InlineTypeUnion7';
import { InlineTypeUnion7Schema } from './InlineTypeUnion7';
import type { InlineTypeUnion8 } from './InlineTypeUnion8';
import { InlineTypeUnion8Schema } from './InlineTypeUnion8';
import type { InlineTypeUnion9 } from './InlineTypeUnion9';
import { InlineTypeUnion9Schema } from './InlineTypeUnion9';
import type { OpenResponsesErrorEvent } from './OpenResponsesErrorEvent';
import { OpenResponsesErrorEventSchema } from './OpenResponsesErrorEvent';
import type { OpenResponsesImageGenCallCompleted } from './OpenResponsesImageGenCallCompleted';
import { OpenResponsesImageGenCallCompletedSchema } from './OpenResponsesImageGenCallCompleted';
import type { OpenResponsesImageGenCallGenerating } from './OpenResponsesImageGenCallGenerating';
import { OpenResponsesImageGenCallGeneratingSchema } from './OpenResponsesImageGenCallGenerating';
import type { OpenResponsesImageGenCallInProgress } from './OpenResponsesImageGenCallInProgress';
import { OpenResponsesImageGenCallInProgressSchema } from './OpenResponsesImageGenCallInProgress';
import type { OpenResponsesImageGenCallPartialImage } from './OpenResponsesImageGenCallPartialImage';
import { OpenResponsesImageGenCallPartialImageSchema } from './OpenResponsesImageGenCallPartialImage';
import type { OpenResponsesReasoningDeltaEvent } from './OpenResponsesReasoningDeltaEvent';
import { OpenResponsesReasoningDeltaEventSchema } from './OpenResponsesReasoningDeltaEvent';
import type { OpenResponsesReasoningDoneEvent } from './OpenResponsesReasoningDoneEvent';
import { OpenResponsesReasoningDoneEventSchema } from './OpenResponsesReasoningDoneEvent';
import type { OpenResponsesReasoningSummaryPartAddedEvent } from './OpenResponsesReasoningSummaryPartAddedEvent';
import { OpenResponsesReasoningSummaryPartAddedEventSchema } from './OpenResponsesReasoningSummaryPartAddedEvent';
import type { OpenResponsesReasoningSummaryTextDeltaEvent } from './OpenResponsesReasoningSummaryTextDeltaEvent';
import { OpenResponsesReasoningSummaryTextDeltaEventSchema } from './OpenResponsesReasoningSummaryTextDeltaEvent';
import type { OpenResponsesReasoningSummaryTextDoneEvent } from './OpenResponsesReasoningSummaryTextDoneEvent';
import { OpenResponsesReasoningSummaryTextDoneEventSchema } from './OpenResponsesReasoningSummaryTextDoneEvent';
export type OpenResponsesStreamEvent = InlineTypeUnion4 | InlineTypeUnion4 | InlineTypeUnion4 | InlineTypeUnion4 | InlineTypeUnion4 | OpenResponsesErrorEvent | InlineTypeUnion5 | InlineTypeUnion5 | InlineTypeUnion6 | InlineTypeUnion6 | InlineTypeUnion7 | InlineTypeUnion8 | InlineTypeUnion9 | InlineTypeUnion10 | InlineTypeUnion11 | InlineTypeUnion12 | InlineTypeUnion13 | OpenResponsesReasoningDeltaEvent | OpenResponsesReasoningDoneEvent | OpenResponsesReasoningSummaryPartAddedEvent | InlineTypeUnion14 | OpenResponsesReasoningSummaryTextDeltaEvent | OpenResponsesReasoningSummaryTextDoneEvent | OpenResponsesImageGenCallInProgress | OpenResponsesImageGenCallGenerating | OpenResponsesImageGenCallPartialImage | OpenResponsesImageGenCallCompleted;

export const OpenResponsesStreamEventSchema: TypedSchema<OpenResponsesStreamEvent> = typed<OpenResponsesStreamEvent>(union(InlineTypeUnion4Schema, InlineTypeUnion4Schema, InlineTypeUnion4Schema, InlineTypeUnion4Schema, InlineTypeUnion4Schema, OpenResponsesErrorEventSchema, InlineTypeUnion5Schema, InlineTypeUnion5Schema, InlineTypeUnion6Schema, InlineTypeUnion6Schema, InlineTypeUnion7Schema, InlineTypeUnion8Schema, InlineTypeUnion9Schema, InlineTypeUnion10Schema, InlineTypeUnion11Schema, InlineTypeUnion12Schema, InlineTypeUnion13Schema, OpenResponsesReasoningDeltaEventSchema, OpenResponsesReasoningDoneEventSchema, OpenResponsesReasoningSummaryPartAddedEventSchema, InlineTypeUnion14Schema, OpenResponsesReasoningSummaryTextDeltaEventSchema, OpenResponsesReasoningSummaryTextDoneEventSchema, OpenResponsesImageGenCallInProgressSchema, OpenResponsesImageGenCallGeneratingSchema, OpenResponsesImageGenCallPartialImageSchema, OpenResponsesImageGenCallCompletedSchema));