import { TypedSchema, literal, typed, union } from '@speakeasy-api/tonic';
export type ProviderName = "AI21" | "AionLabs" | "Alibaba" | "Amazon Bedrock" | "Anthropic" | "Arcee" | "AtlasCloud" | "Avian" | "Azure" | "BaseTen" | "Black Forest Labs" | "Cerebras" | "Chutes" | "Cirrascale" | "Clarifai" | "Cloudflare" | "Cohere" | "Crusoe" | "DeepInfra" | "DeepSeek" | "Featherless" | "Fireworks" | "Friendli" | "GMICloud" | "Google" | "Google AI Studio" | "Groq" | "Hyperbolic" | "Inception" | "InferenceNet" | "Infermatic" | "Inflection" | "Liquid" | "Mancer 2" | "Minimax" | "ModelRun" | "Mistral" | "Modular" | "Moonshot AI" | "Morph" | "NCompass" | "Nebius" | "NextBit" | "Novita" | "Nvidia" | "OpenAI" | "OpenInference" | "Parasail" | "Perplexity" | "Phala" | "Relace" | "SambaNova" | "SiliconFlow" | "Stealth" | "Switchpoint" | "Targon" | "Together" | "Venice" | "WandB" | "xAI" | "Z.AI" | "FakeProvider";

export const ProviderNameSchema: TypedSchema<ProviderName> = typed<ProviderName>(union(
  literal("AI21"),
  literal("AionLabs"),
  literal("Alibaba"),
  literal("Amazon Bedrock"),
  literal("Anthropic"),
  literal("Arcee"),
  literal("AtlasCloud"),
  literal("Avian"),
  literal("Azure"),
  literal("BaseTen"),
  literal("Black Forest Labs"),
  literal("Cerebras"),
  literal("Chutes"),
  literal("Cirrascale"),
  literal("Clarifai"),
  literal("Cloudflare"),
  literal("Cohere"),
  literal("Crusoe"),
  literal("DeepInfra"),
  literal("DeepSeek"),
  literal("Featherless"),
  literal("Fireworks"),
  literal("Friendli"),
  literal("GMICloud"),
  literal("Google"),
  literal("Google AI Studio"),
  literal("Groq"),
  literal("Hyperbolic"),
  literal("Inception"),
  literal("InferenceNet"),
  literal("Infermatic"),
  literal("Inflection"),
  literal("Liquid"),
  literal("Mancer 2"),
  literal("Minimax"),
  literal("ModelRun"),
  literal("Mistral"),
  literal("Modular"),
  literal("Moonshot AI"),
  literal("Morph"),
  literal("NCompass"),
  literal("Nebius"),
  literal("NextBit"),
  literal("Novita"),
  literal("Nvidia"),
  literal("OpenAI"),
  literal("OpenInference"),
  literal("Parasail"),
  literal("Perplexity"),
  literal("Phala"),
  literal("Relace"),
  literal("SambaNova"),
  literal("SiliconFlow"),
  literal("Stealth"),
  literal("Switchpoint"),
  literal("Targon"),
  literal("Together"),
  literal("Venice"),
  literal("WandB"),
  literal("xAI"),
  literal("Z.AI"),
  literal("FakeProvider"),
));

/**
 * Enum values for ProviderName.
 * Use these constants for type-safe comparisons.
 */
export const ProviderName = {
  AI21: "AI21" as const,
  AION_LABS: "AionLabs" as const,
  ALIBABA: "Alibaba" as const,
  AMAZON_BEDROCK: "Amazon Bedrock" as const,
  ANTHROPIC: "Anthropic" as const,
  ARCEE: "Arcee" as const,
  ATLAS_CLOUD: "AtlasCloud" as const,
  AVIAN: "Avian" as const,
  AZURE: "Azure" as const,
  BASE_TEN: "BaseTen" as const,
  BLACK_FOREST_LABS: "Black Forest Labs" as const,
  CEREBRAS: "Cerebras" as const,
  CHUTES: "Chutes" as const,
  CIRRASCALE: "Cirrascale" as const,
  CLARIFAI: "Clarifai" as const,
  CLOUDFLARE: "Cloudflare" as const,
  COHERE: "Cohere" as const,
  CRUSOE: "Crusoe" as const,
  DEEP_INFRA: "DeepInfra" as const,
  DEEP_SEEK: "DeepSeek" as const,
  FEATHERLESS: "Featherless" as const,
  FIREWORKS: "Fireworks" as const,
  FRIENDLI: "Friendli" as const,
  GMI_CLOUD: "GMICloud" as const,
  GOOGLE: "Google" as const,
  GOOGLE_AI_STUDIO: "Google AI Studio" as const,
  GROQ: "Groq" as const,
  HYPERBOLIC: "Hyperbolic" as const,
  INCEPTION: "Inception" as const,
  INFERENCE_NET: "InferenceNet" as const,
  INFERMATIC: "Infermatic" as const,
  INFLECTION: "Inflection" as const,
  LIQUID: "Liquid" as const,
  MANCER_2: "Mancer 2" as const,
  MINIMAX: "Minimax" as const,
  MODEL_RUN: "ModelRun" as const,
  MISTRAL: "Mistral" as const,
  MODULAR: "Modular" as const,
  MOONSHOT_AI: "Moonshot AI" as const,
  MORPH: "Morph" as const,
  N_COMPASS: "NCompass" as const,
  NEBIUS: "Nebius" as const,
  NEXT_BIT: "NextBit" as const,
  NOVITA: "Novita" as const,
  NVIDIA: "Nvidia" as const,
  OPEN_AI: "OpenAI" as const,
  OPEN_INFERENCE: "OpenInference" as const,
  PARASAIL: "Parasail" as const,
  PERPLEXITY: "Perplexity" as const,
  PHALA: "Phala" as const,
  RELACE: "Relace" as const,
  SAMBA_NOVA: "SambaNova" as const,
  SILICON_FLOW: "SiliconFlow" as const,
  STEALTH: "Stealth" as const,
  SWITCHPOINT: "Switchpoint" as const,
  TARGON: "Targon" as const,
  TOGETHER: "Together" as const,
  VENICE: "Venice" as const,
  WAND_B: "WandB" as const,
  X_AI: "xAI" as const,
  Z_AI: "Z.AI" as const,
  FAKE_PROVIDER: "FakeProvider" as const,
} as const;