import { TypedSchema, array, number, object, optional, typed } from '@speakeasy-api/tonic';

import type { AccountTaxIdsItemUnion } from './AccountTaxIdsItemUnion';
import { AccountTaxIdsItemUnionSchema } from './AccountTaxIdsItemUnion';
import type { ConnectAccountReference } from './ConnectAccountReference';
import { ConnectAccountReferenceSchema } from './ConnectAccountReference';
/**
 * InvoiceSettingSubscriptionSchedulePhaseSetting
 *
 * 
 */
export interface InvoiceSettingSubscriptionSchedulePhaseSetting {
  /**
   * The account tax IDs associated with this phase of the subscription schedule. Will be set on invoices generated by this phase of the subscription schedule.
   */
  accountTaxIds?: Array<AccountTaxIdsItemUnion>;
  /**
   * Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
   */
  daysUntilDue?: number;
  /**
   * The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
   */
  issuer?: ConnectAccountReference;
}

export const InvoiceSettingSubscriptionSchedulePhaseSettingSchema: TypedSchema<InvoiceSettingSubscriptionSchedulePhaseSetting> = typed<InvoiceSettingSubscriptionSchedulePhaseSetting>(object({
  get accountTaxIds() { return optional(array(AccountTaxIdsItemUnionSchema)) },
  daysUntilDue: optional(number()),
  get issuer() { return optional(ConnectAccountReferenceSchema) },
}));