import { TypedSchema, number, object, optional, typed } from '@speakeasy-api/tonic';

import type { ConnectAccountReference } from './ConnectAccountReference';
import { ConnectAccountReferenceSchema } from './ConnectAccountReference';
/**
 * InvoiceSettingQuoteSetting
 *
 * 
 */
export interface InvoiceSettingQuoteSetting {
  /**
   * Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
   */
  daysUntilDue?: number;
  /**
   * ConnectAccountReference
   *
   * 
   */
  issuer: ConnectAccountReference;
}

export const InvoiceSettingQuoteSettingSchema: TypedSchema<InvoiceSettingQuoteSetting> = typed<InvoiceSettingQuoteSetting>(object({
  daysUntilDue: optional(number()),
  issuer: ConnectAccountReferenceSchema,
}));