import { TypedSchema, array, number, object, optional, typed } from '@speakeasy-api/tonic';

import type { AccountTaxIdsItemUnion } from './AccountTaxIdsItemUnion';
import { AccountTaxIdsItemUnionSchema } from './AccountTaxIdsItemUnion';
import type { ConnectAccountReference } from './ConnectAccountReference';
import { ConnectAccountReferenceSchema } from './ConnectAccountReference';
/**
 * InvoiceSettingSubscriptionScheduleSetting
 *
 * 
 */
export interface InvoiceSettingSubscriptionScheduleSetting {
  /**
   * The account tax IDs associated with the subscription schedule. Will be set on invoices generated by the subscription schedule.
   */
  accountTaxIds?: Array<AccountTaxIdsItemUnion>;
  /**
   * Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
   */
  daysUntilDue?: number;
  /**
   * ConnectAccountReference
   *
   * 
   */
  issuer: ConnectAccountReference;
}

export const InvoiceSettingSubscriptionScheduleSettingSchema: TypedSchema<InvoiceSettingSubscriptionScheduleSetting> = typed<InvoiceSettingSubscriptionScheduleSetting>(object({
  get accountTaxIds() { return optional(array(AccountTaxIdsItemUnionSchema)) },
  daysUntilDue: optional(number()),
  issuer: ConnectAccountReferenceSchema,
}));