import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * mandate_paypal
 *
 * 
 */
export interface MandatePaypal {
  /**
   * The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
   */
  billingAgreementId?: string;
  /**
   * PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
   */
  payerId?: string;
}

export const MandatePaypalSchema: TypedSchema<MandatePaypal> = typed<MandatePaypal>(object({
  billingAgreementId: optional(string()),
  payerId: optional(string()),
}));