import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * payment_method_details_grabpay
 *
 * 
 */
export interface PaymentMethodDetailsGrabpay {
  /**
   * Unique transaction id generated by GrabPay
   */
  transactionId?: string;
}

export const PaymentMethodDetailsGrabpaySchema: TypedSchema<PaymentMethodDetailsGrabpay> = typed<PaymentMethodDetailsGrabpay>(object({
  transactionId: optional(string()),
}));