import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * payment_method_details_pix
 *
 * 
 */
export interface PaymentMethodDetailsPix {
  /**
   * Unique transaction id generated by BCB
   */
  bankTransactionId?: string;
}

export const PaymentMethodDetailsPixSchema: TypedSchema<PaymentMethodDetailsPix> = typed<PaymentMethodDetailsPix>(object({
  bankTransactionId: optional(string()),
}));