import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * payment_method_details_fpx
 *
 * 
 */
export interface PaymentMethodDetailsFpx {
  /**
   * The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
   */
  bank: string;
  /**
   * Unique transaction id generated by FPX for every request from the merchant
   */
  transactionId?: string;
}

export const PaymentMethodDetailsFpxSchema: TypedSchema<PaymentMethodDetailsFpx> = typed<PaymentMethodDetailsFpx>(object({
  bank: string(),
  transactionId: optional(string()),
}));