import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * payment_method_details_promptpay
 *
 * 
 */
export interface PaymentMethodDetailsPromptpay {
  /**
   * Bill reference generated by PromptPay
   */
  reference?: string;
}

export const PaymentMethodDetailsPromptpaySchema: TypedSchema<PaymentMethodDetailsPromptpay> = typed<PaymentMethodDetailsPromptpay>(object({
  reference: optional(string()),
}));