import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { PaypalSellerProtection } from './PaypalSellerProtection';
import { PaypalSellerProtectionSchema } from './PaypalSellerProtection';
/**
 * payment_method_details_paypal
 *
 * 
 */
export interface PaymentMethodDetailsPaypal {
  /**
   * Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  country?: string;
  /**
   * Owner's email. Values are provided by PayPal directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  payerEmail?: string;
  /**
   * PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
   */
  payerId?: string;
  /**
   * Owner's full name. Values provided by PayPal directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  payerName?: string;
  /**
   * The level of protection offered as defined by PayPal Seller Protection for Merchants, for this transaction.
   */
  sellerProtection?: PaypalSellerProtection;
  /**
   * A unique ID generated by PayPal for this transaction.
   */
  transactionId?: string;
}

export const PaymentMethodDetailsPaypalSchema: TypedSchema<PaymentMethodDetailsPaypal> = typed<PaymentMethodDetailsPaypal>(object({
  country: optional(string()),
  payerEmail: optional(string()),
  payerId: optional(string()),
  payerName: optional(string()),
  get sellerProtection() { return optional(PaypalSellerProtectionSchema) },
  transactionId: optional(string()),
}));