import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { GeneratedSepaDebitMandateOrRef } from './GeneratedSepaDebitMandateOrRef';
import { GeneratedSepaDebitMandateOrRefSchema } from './GeneratedSepaDebitMandateOrRef';
import type { GeneratedSepaDebitOrRef } from './GeneratedSepaDebitOrRef';
import { GeneratedSepaDebitOrRefSchema } from './GeneratedSepaDebitOrRef';
/**
 * payment_method_details_sofort
 *
 * 
 */
export interface PaymentMethodDetailsSofort {
  /**
   * Bank code of bank associated with the bank account.
   */
  bankCode?: string;
  /**
   * Name of the bank associated with the bank account.
   */
  bankName?: string;
  /**
   * Bank Identifier Code of the bank associated with the bank account.
   */
  bic?: string;
  /**
   * Two-letter ISO code representing the country the bank account is located in.
   */
  country?: string;
  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  generatedSepaDebit?: GeneratedSepaDebitOrRef;
  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  generatedSepaDebitMandate?: GeneratedSepaDebitMandateOrRef;
  /**
   * Last four characters of the IBAN.
   */
  ibanLast4?: string;
  /**
   * Preferred language of the SOFORT authorization page that the customer is redirected to.
Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
   */
  preferredLanguage?: string;
  /**
   * Owner's verified full name. Values are verified or provided by SOFORT directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  verifiedName?: string;
}

export const PaymentMethodDetailsSofortSchema: TypedSchema<PaymentMethodDetailsSofort> = typed<PaymentMethodDetailsSofort>(object({
  bankCode: optional(string()),
  bankName: optional(string()),
  bic: optional(string()),
  country: optional(string()),
  get generatedSepaDebit() { return optional(GeneratedSepaDebitOrRefSchema) },
  get generatedSepaDebitMandate() { return optional(GeneratedSepaDebitMandateOrRefSchema) },
  ibanLast4: optional(string()),
  preferredLanguage: optional(string()),
  verifiedName: optional(string()),
}));