import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostCustomersCustomerSubscriptionsRequestCustomerBalanceObject } from './PostCustomersCustomerSubscriptionsRequestCustomerBalanceObject';
import { PostCustomersCustomerSubscriptionsRequestCustomerBalanceObjectSchema } from './PostCustomersCustomerSubscriptionsRequestCustomerBalanceObject';
export type PostCustomersCustomerSubscriptionsRequestCustomerBalance = PostCustomersCustomerSubscriptionsRequestCustomerBalanceObject | string;

export const PostCustomersCustomerSubscriptionsRequestCustomerBalanceSchema: TypedSchema<PostCustomersCustomerSubscriptionsRequestCustomerBalance> = typed<PostCustomersCustomerSubscriptionsRequestCustomerBalance>(union(PostCustomersCustomerSubscriptionsRequestCustomerBalanceObjectSchema, string()));