import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject } from './PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject';
import { PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObjectSchema } from './PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject';
export type PostSubscriptionItemsRequestBillingThresholds = PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject | string;

export const PostSubscriptionItemsRequestBillingThresholdsSchema: TypedSchema<PostSubscriptionItemsRequestBillingThresholds> = typed<PostSubscriptionItemsRequestBillingThresholds>(union(PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObjectSchema, string()));