import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObject } from './PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObject';
import { PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObjectSchema } from './PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObject';
export type PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetails = PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObject | string;

export const PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsSchema: TypedSchema<PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetails> = typed<PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetails>(union(PostPaymentRecordsIdReportPaymentAttemptInformationalRequestShippingDetailsObjectSchema, string()));