import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObject } from './PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObject';
import { PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObjectSchema } from './PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObject';
export type PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollection = PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObject | string;

export const PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionSchema: TypedSchema<PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollection> = typed<PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollection>(union(PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestPauseCollectionObjectSchema, string()));