import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObject } from './PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObject';
import { PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObjectSchema } from './PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObject';
export type PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierText = PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObject | string;

export const PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextSchema: TypedSchema<PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierText> = typed<PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierText>(union(PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierTextObjectSchema, string()));