import { TypedSchema, array, boolean, number, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { DefaultPostAccountsRequestMetadata } from './DefaultPostAccountsRequestMetadata';
import { DefaultPostAccountsRequestMetadataSchema } from './DefaultPostAccountsRequestMetadata';
import type { PostPlansRequestProduct } from './PostPlansRequestProduct';
import { PostPlansRequestProductSchema } from './PostPlansRequestProduct';
import type { PostPlansRequestTiersItem } from './PostPlansRequestTiersItem';
import { PostPlansRequestTiersItemSchema } from './PostPlansRequestTiersItem';
import type { PostPlansRequestTransformUsage } from './PostPlansRequestTransformUsage';
import { PostPlansRequestTransformUsageSchema } from './PostPlansRequestTransformUsage';
export interface PostPlansRequest {
  /**
   * Whether the plan is currently available for new subscriptions. Defaults to `true`.
   */
  active?: boolean;
  /**
   * A positive integer in cents (or local equivalent) (or 0 for a free plan) representing how much to charge on a recurring basis.
   */
  amount?: number;
  /**
   * Same as `amount`, but accepts a decimal value with at most 12 decimal places. Only one of `amount` and `amount_decimal` can be set.
   */
  amountDecimal?: string;
  /**
   * Describes how to compute the price per period. Either `per_unit` or `tiered`. `per_unit` indicates that the fixed amount (specified in `amount`) will be charged per unit in `quantity` (for plans with `usage_type=licensed`), or per unit of total usage (for plans with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiers_mode` attributes.
   */
  billingScheme?: string;
  /**
   * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
   */
  currency: string;
  /**
   * Specifies which fields in the response should be expanded.
   */
  expand?: Array<string>;
  /**
   * An identifier randomly generated by Stripe. Used to identify this plan when subscribing a customer. You can optionally override this ID, but the ID must be unique across all plans in your Stripe account. You can, however, use the same plan ID in both live and test modes.
   */
  id?: string;
  /**
   * Specifies billing frequency. Either `day`, `week`, `month` or `year`.
   */
  interval: string;
  /**
   * The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
   */
  intervalCount?: number;
  /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
   */
  metadata?: DefaultPostAccountsRequestMetadata;
  /**
   * The meter tracking the usage of a metered price
   */
  meter?: string;
  /**
   * A brief description of the plan, hidden from customers.
   */
  nickname?: string;
  product?: PostPlansRequestProduct;
  /**
   * Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
   */
  tiers?: Array<PostPlansRequestTiersItem>;
  /**
   * Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
   */
  tiersMode?: string;
  /**
   * transform_usage_param
   *
   * Apply a transformation to the reported usage or set quantity before computing the billed price. Cannot be combined with `tiers`.
   */
  transformUsage?: PostPlansRequestTransformUsage;
  /**
   * Default number of trial days when subscribing a customer to this plan using [`trial_from_plan=true`](https://stripe.com/docs/api#create_subscription-trial_from_plan).
   */
  trialPeriodDays?: number;
  /**
   * Configures how the quantity per period should be determined. Can be either `metered` or `licensed`. `licensed` automatically bills the `quantity` set when adding it to a subscription. `metered` aggregates the total usage based on usage records. Defaults to `licensed`.
   */
  usageType?: string;
}

export const PostPlansRequestSchema: TypedSchema<PostPlansRequest> = typed<PostPlansRequest>(object({
  active: optional(boolean()),
  amount: optional(number()),
  amountDecimal: optional(string()),
  billingScheme: optional(string()),
  currency: string(),
  expand: optional(array(string())),
  id: optional(string()),
  interval: string(),
  intervalCount: optional(number()),
  get metadata() { return optional(DefaultPostAccountsRequestMetadataSchema) },
  meter: optional(string()),
  nickname: optional(string()),
  get product() { return optional(PostPlansRequestProductSchema) },
  get tiers() { return optional(array(PostPlansRequestTiersItemSchema)) },
  tiersMode: optional(string()),
  get transformUsage() { return optional(PostPlansRequestTransformUsageSchema) },
  trialPeriodDays: optional(number()),
  usageType: optional(string()),
}));