import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostTerminalConfigurationsConfigurationRequestVerifoneP400Object } from './PostTerminalConfigurationsConfigurationRequestVerifoneP400Object';
import { PostTerminalConfigurationsConfigurationRequestVerifoneP400ObjectSchema } from './PostTerminalConfigurationsConfigurationRequestVerifoneP400Object';
export type PostTerminalConfigurationsConfigurationRequestVerifoneP400 = PostTerminalConfigurationsConfigurationRequestVerifoneP400Object | string;

export const PostTerminalConfigurationsConfigurationRequestVerifoneP400Schema: TypedSchema<PostTerminalConfigurationsConfigurationRequestVerifoneP400> = typed<PostTerminalConfigurationsConfigurationRequestVerifoneP400>(union(PostTerminalConfigurationsConfigurationRequestVerifoneP400ObjectSchema, string()));