import { TypedSchema, string, typed, union } from '@speakeasy-api/tonic';

import type { PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject } from './PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject';
import { PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObjectSchema } from './PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject';
export type PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholds = PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObject | string;

export const PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsSchema: TypedSchema<PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholds> = typed<PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholds>(union(PostCustomersCustomerSubscriptionsRequestItemsItemBillingThresholdsObjectSchema, string()));