import { TypedSchema, array, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { DefaultPostAccountsRequestMetadata } from './DefaultPostAccountsRequestMetadata';
import { DefaultPostAccountsRequestMetadataSchema } from './DefaultPostAccountsRequestMetadata';
export interface PostTerminalReadersRequest {
  /**
   * Specifies which fields in the response should be expanded.
   */
  expand?: Array<string>;
  /**
   * Custom label given to the reader for easier identification. If no label is specified, the registration code will be used.
   */
  label?: string;
  /**
   * The location to assign the reader to.
   */
  location?: string;
  /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
   */
  metadata?: DefaultPostAccountsRequestMetadata;
  /**
   * A code generated by the reader used for registering to an account.
   */
  registrationCode: string;
}

export const PostTerminalReadersRequestSchema: TypedSchema<PostTerminalReadersRequest> = typed<PostTerminalReadersRequest>(object({
  expand: optional(array(string())),
  label: optional(string()),
  location: optional(string()),
  get metadata() { return optional(DefaultPostAccountsRequestMetadataSchema) },
  registrationCode: string(),
}));