import { TypedSchema, number, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { BalanceTransactionOrRef } from './BalanceTransactionOrRef';
import { BalanceTransactionOrRefSchema } from './BalanceTransactionOrRef';
import type { ChargeOrRef } from './ChargeOrRef';
import { ChargeOrRefSchema } from './ChargeOrRef';
import type { FailureBalanceTransactionOrRef } from './FailureBalanceTransactionOrRef';
import { FailureBalanceTransactionOrRefSchema } from './FailureBalanceTransactionOrRef';
import type { MetadataProperty } from './MetadataProperty';
import { MetadataPropertySchema } from './MetadataProperty';
import type { PaymentFlowsPaymentIntentPresentmentDetails } from './PaymentFlowsPaymentIntentPresentmentDetails';
import { PaymentFlowsPaymentIntentPresentmentDetailsSchema } from './PaymentFlowsPaymentIntentPresentmentDetails';
import type { PaymentIntentOrRef } from './PaymentIntentOrRef';
import { PaymentIntentOrRefSchema } from './PaymentIntentOrRef';
import type { RefundDestinationDetails } from './RefundDestinationDetails';
import { RefundDestinationDetailsSchema } from './RefundDestinationDetails';
import type { RefundNextAction } from './RefundNextAction';
import { RefundNextActionSchema } from './RefundNextAction';
import type { SourceTransferReversalOrRef } from './SourceTransferReversalOrRef';
import { SourceTransferReversalOrRefSchema } from './SourceTransferReversalOrRef';
import type { TransferReversalOrRef } from './TransferReversalOrRef';
import { TransferReversalOrRefSchema } from './TransferReversalOrRef';
/**
 * Refund
 *
 * Refund objects allow you to refund a previously created charge that isn't
refunded yet. Funds are refunded to the credit or debit card that's
initially charged.

Related guide: [Refunds](https://stripe.com/docs/refunds)
 */
export interface Refund {
  /**
   * Amount, in cents (or local equivalent).
   */
  amount: number;
  /**
   * Balance transaction that describes the impact on your account balance.
   */
  balanceTransaction?: BalanceTransactionOrRef;
  /**
   * ID of the charge that's refunded.
   */
  charge?: ChargeOrRef;
  /**
   * Time at which the object was created. Measured in seconds since the Unix epoch.
   */
  created: number;
  /**
   * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
   */
  currency: string;
  /**
   * An arbitrary string attached to the object. You can use this for displaying to users (available on non-card refunds only).
   */
  description?: string;
  /**
   * refund_destination_details
   *
   * 
   */
  destinationDetails?: RefundDestinationDetails;
  /**
   * After the refund fails, this balance transaction describes the adjustment made on your account balance that reverses the initial balance transaction.
   */
  failureBalanceTransaction?: FailureBalanceTransactionOrRef;
  /**
   * Provides the reason for the refund failure. Possible values are: `lost_or_stolen_card`, `expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, `declined`, `merchant_request`, or `unknown`.
   */
  failureReason?: string;
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * For payment methods without native refund support (for example, Konbini, PromptPay), provide an email address for the customer to receive refund instructions.
   */
  instructionsEmail?: string;
  /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
   */
  metadata?: MetadataProperty;
  /**
   * RefundNextAction
   *
   * 
   */
  nextAction?: RefundNextAction;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * ID of the PaymentIntent that's refunded.
   */
  paymentIntent?: PaymentIntentOrRef;
  /**
   * Provides the reason for why the refund is pending. Possible values are: `processing`, `insufficient_funds`, or `charge_pending`.
   */
  pendingReason?: string;
  /**
   * PaymentFlowsPaymentIntentPresentmentDetails
   *
   * 
   */
  presentmentDetails?: PaymentFlowsPaymentIntentPresentmentDetails;
  /**
   * Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
   */
  reason?: string;
  /**
   * This is the transaction number that appears on email receipts sent for this refund.
   */
  receiptNumber?: string;
  /**
   * The transfer reversal that's associated with the refund. Only present if the charge came from another Stripe account.
   */
  sourceTransferReversal?: SourceTransferReversalOrRef;
  /**
   * Status of the refund. This can be `pending`, `requires_action`, `succeeded`, `failed`, or `canceled`. Learn more about [failed refunds](https://stripe.com/docs/refunds#failed-refunds).
   */
  status?: string;
  /**
   * This refers to the transfer reversal object if the accompanying transfer reverses. This is only applicable if the charge was created using the destination parameter.
   */
  transferReversal?: TransferReversalOrRef;
}

export const RefundSchema: TypedSchema<Refund> = typed<Refund>(object({
  amount: number(),
  get balanceTransaction() { return optional(BalanceTransactionOrRefSchema) },
  get charge() { return optional(ChargeOrRefSchema) },
  created: number(),
  currency: string(),
  description: optional(string()),
  get destinationDetails() { return optional(RefundDestinationDetailsSchema) },
  get failureBalanceTransaction() { return optional(FailureBalanceTransactionOrRefSchema) },
  failureReason: optional(string()),
  id: string(),
  instructionsEmail: optional(string()),
  get metadata() { return optional(MetadataPropertySchema) },
  get nextAction() { return optional(RefundNextActionSchema) },
  object: string(),
  get paymentIntent() { return optional(PaymentIntentOrRefSchema) },
  pendingReason: optional(string()),
  get presentmentDetails() { return optional(PaymentFlowsPaymentIntentPresentmentDetailsSchema) },
  reason: optional(string()),
  receiptNumber: optional(string()),
  get sourceTransferReversal() { return optional(SourceTransferReversalOrRefSchema) },
  status: optional(string()),
  get transferReversal() { return optional(TransferReversalOrRefSchema) },
}));