import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';
/**
 * setup_intent_payment_method_options_paypal
 *
 * 
 */
export interface SetupIntentPaymentMethodOptionsPaypal {
  /**
   * The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
   */
  billingAgreementId?: string;
}

export const SetupIntentPaymentMethodOptionsPaypalSchema: TypedSchema<SetupIntentPaymentMethodOptionsPaypal> = typed<SetupIntentPaymentMethodOptionsPaypal>(object({
  billingAgreementId: optional(string()),
}));