import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { GeneratedSepaDebitMandateOrRef } from './GeneratedSepaDebitMandateOrRef';
import { GeneratedSepaDebitMandateOrRefSchema } from './GeneratedSepaDebitMandateOrRef';
import type { GeneratedSepaDebitOrRef } from './GeneratedSepaDebitOrRef';
import { GeneratedSepaDebitOrRefSchema } from './GeneratedSepaDebitOrRef';
/**
 * setup_attempt_payment_method_details_ideal
 *
 * 
 */
export interface SetupAttemptPaymentMethodDetailsIdeal {
  /**
   * The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
   */
  bank?: string;
  /**
   * The Bank Identifier Code of the customer's bank.
   */
  bic?: string;
  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
   */
  generatedSepaDebit?: GeneratedSepaDebitOrRef;
  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
   */
  generatedSepaDebitMandate?: GeneratedSepaDebitMandateOrRef;
  /**
   * Last four characters of the IBAN.
   */
  ibanLast4?: string;
  /**
   * Owner's verified full name. Values are verified or provided by iDEAL directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  verifiedName?: string;
}

export const SetupAttemptPaymentMethodDetailsIdealSchema: TypedSchema<SetupAttemptPaymentMethodDetailsIdeal> = typed<SetupAttemptPaymentMethodDetailsIdeal>(object({
  bank: optional(string()),
  bic: optional(string()),
  get generatedSepaDebit() { return optional(GeneratedSepaDebitOrRefSchema) },
  get generatedSepaDebitMandate() { return optional(GeneratedSepaDebitMandateOrRefSchema) },
  ibanLast4: optional(string()),
  verifiedName: optional(string()),
}));