import { TypedSchema, object, optional, string, typed } from '@speakeasy-api/tonic';

import type { GeneratedSepaDebitMandateOrRef } from './GeneratedSepaDebitMandateOrRef';
import { GeneratedSepaDebitMandateOrRefSchema } from './GeneratedSepaDebitMandateOrRef';
import type { GeneratedSepaDebitOrRef } from './GeneratedSepaDebitOrRef';
import { GeneratedSepaDebitOrRefSchema } from './GeneratedSepaDebitOrRef';
/**
 * setup_attempt_payment_method_details_sofort
 *
 * 
 */
export interface SetupAttemptPaymentMethodDetailsSofort {
  /**
   * Bank code of bank associated with the bank account.
   */
  bankCode?: string;
  /**
   * Name of the bank associated with the bank account.
   */
  bankName?: string;
  /**
   * Bank Identifier Code of the bank associated with the bank account.
   */
  bic?: string;
  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
   */
  generatedSepaDebit?: GeneratedSepaDebitOrRef;
  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
   */
  generatedSepaDebitMandate?: GeneratedSepaDebitMandateOrRef;
  /**
   * Last four characters of the IBAN.
   */
  ibanLast4?: string;
  /**
   * Preferred language of the Sofort authorization page that the customer is redirected to.
Can be one of `en`, `de`, `fr`, or `nl`
   */
  preferredLanguage?: string;
  /**
   * Owner's verified full name. Values are verified or provided by Sofort directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  verifiedName?: string;
}

export const SetupAttemptPaymentMethodDetailsSofortSchema: TypedSchema<SetupAttemptPaymentMethodDetailsSofort> = typed<SetupAttemptPaymentMethodDetailsSofort>(object({
  bankCode: optional(string()),
  bankName: optional(string()),
  bic: optional(string()),
  get generatedSepaDebit() { return optional(GeneratedSepaDebitOrRefSchema) },
  get generatedSepaDebitMandate() { return optional(GeneratedSepaDebitMandateOrRefSchema) },
  ibanLast4: optional(string()),
  preferredLanguage: optional(string()),
  verifiedName: optional(string()),
}));