import { TypedSchema, object, optional, typed } from '@speakeasy-api/tonic';

import type { GeneratedCardOrRef } from './GeneratedCardOrRef';
import { GeneratedCardOrRefSchema } from './GeneratedCardOrRef';
import type { PaymentMethodDetailsCardPresentOffline } from './PaymentMethodDetailsCardPresentOffline';
import { PaymentMethodDetailsCardPresentOfflineSchema } from './PaymentMethodDetailsCardPresentOffline';
/**
 * setup_attempt_payment_method_details_card_present
 *
 * 
 */
export interface SetupAttemptPaymentMethodDetailsCardPresent {
  /**
   * The ID of the Card PaymentMethod which was generated by this SetupAttempt.
   */
  generatedCard?: GeneratedCardOrRef;
  /**
   * Details about payments collected offline.
   */
  offline?: PaymentMethodDetailsCardPresentOffline;
}

export const SetupAttemptPaymentMethodDetailsCardPresentSchema: TypedSchema<SetupAttemptPaymentMethodDetailsCardPresent> = typed<SetupAttemptPaymentMethodDetailsCardPresent>(object({
  get generatedCard() { return optional(GeneratedCardOrRefSchema) },
  get offline() { return optional(PaymentMethodDetailsCardPresentOfflineSchema) },
}));