import { TypedSchema, array, object, optional, typed } from '@speakeasy-api/tonic';

import type { AccountTaxIdsItemUnion } from './AccountTaxIdsItemUnion';
import { AccountTaxIdsItemUnionSchema } from './AccountTaxIdsItemUnion';
import type { ConnectAccountReference } from './ConnectAccountReference';
import { ConnectAccountReferenceSchema } from './ConnectAccountReference';
/**
 * SubscriptionsResourceSubscriptionInvoiceSettings
 *
 * 
 */
export interface SubscriptionsResourceSubscriptionInvoiceSettings {
  /**
   * The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
   */
  accountTaxIds?: Array<AccountTaxIdsItemUnion>;
  /**
   * ConnectAccountReference
   *
   * 
   */
  issuer: ConnectAccountReference;
}

export const SubscriptionsResourceSubscriptionInvoiceSettingsSchema: TypedSchema<SubscriptionsResourceSubscriptionInvoiceSettings> = typed<SubscriptionsResourceSubscriptionInvoiceSettings>(object({
  get accountTaxIds() { return optional(array(AccountTaxIdsItemUnionSchema)) },
  issuer: ConnectAccountReferenceSchema,
}));