import { string, typed, union } from '@speakeasy-api/tonic';
import type { TypedSchema } from '@speakeasy-api/tonic';

import type { PaymentMethod } from './PaymentMethod';
import { PaymentMethodSchema } from './PaymentMethod';
/**
 * The ID of the Card PaymentMethod which was generated by this SetupAttempt.
 */
export type GeneratedCardOrRef = string | PaymentMethod;

export const GeneratedCardOrRefSchema: TypedSchema<GeneratedCardOrRef> = typed<GeneratedCardOrRef>(union(string(), PaymentMethodSchema));
