import { string, typed, union } from '@speakeasy-api/tonic';
import type { TypedSchema } from '@speakeasy-api/tonic';

import type { PaymentMethod } from './PaymentMethod';
import { PaymentMethodSchema } from './PaymentMethod';
/**
 * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
 */
export type GeneratedSepaDebitOrRef = string | PaymentMethod;

export const GeneratedSepaDebitOrRefSchema: TypedSchema<GeneratedSepaDebitOrRef> = typed<GeneratedSepaDebitOrRef>(union(string(), PaymentMethodSchema));
