import { string, typed, union } from '@speakeasy-api/tonic';
import type { TypedSchema } from '@speakeasy-api/tonic';

import type { Mandate } from './Mandate';
import { MandateSchema } from './Mandate';
/**
 * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
 */
export type GeneratedSepaDebitMandateOrRef = string | Mandate;

export const GeneratedSepaDebitMandateOrRefSchema: TypedSchema<GeneratedSepaDebitMandateOrRef> = typed<GeneratedSepaDebitMandateOrRef>(union(string(), MandateSchema));
