import { string, typed, union } from '@speakeasy-api/tonic';
import type { TypedSchema } from '@speakeasy-api/tonic';

import type { Mandate } from './Mandate';
import { MandateSchema } from './Mandate';
/**
 * ID of the single_use Mandate generated by the SetupIntent.
 */
export type SingleUseMandateOrRef = string | Mandate;

export const SingleUseMandateOrRefSchema: TypedSchema<SingleUseMandateOrRef> = typed<SingleUseMandateOrRef>(union(string(), MandateSchema));
