// Generated types from OpenAPI specification

export * from './errors';
export * from './Booking';
export { BookingSchema } from './Booking';
export * from './BookingPayment';
export { BookingPaymentSchema } from './BookingPayment';
export * from './CreateBookingPaymentUnion';
export { CreateBookingPaymentUnionSchema } from './CreateBookingPaymentUnion';
export * from './CreateBookingUnion';
export { CreateBookingUnionSchema } from './CreateBookingUnion';
export * from './GetBookingsUnion';
export { GetBookingsUnionSchema } from './GetBookingsUnion';
export * from './GetBookingsUnionUnion';
export { GetBookingsUnionUnionSchema } from './GetBookingsUnionUnion';
export * from './GetStationsUnion';
export { GetStationsUnionSchema } from './GetStationsUnion';
export * from './GetTripsUnion';
export { GetTripsUnionSchema } from './GetTripsUnion';
export * from './GetTripsUnionUnion';
export { GetTripsUnionUnionSchema } from './GetTripsUnionUnion';
export * from './LinksBooking';
export { LinksBookingSchema } from './LinksBooking';
export * from './LinksDestination';
export { LinksDestinationSchema } from './LinksDestination';
export * from './LinksOrigin';
export { LinksOriginSchema } from './LinksOrigin';
export * from './LinksPagination';
export { LinksPaginationSchema } from './LinksPagination';
export * from './LinksSelf';
export { LinksSelfSchema } from './LinksSelf';
export * from './Problem';
export { ProblemSchema } from './Problem';
export * from './SourceUnion';
export { SourceUnionSchema } from './SourceUnion';
export * from './SourceUnionObject';
export { SourceUnionObjectSchema } from './SourceUnionObject';
export * from './SourceUnionObject2';
export { SourceUnionObject2Schema } from './SourceUnionObject2';
export * from './Station';
export { StationSchema } from './Station';
export * from './Trip';
export { TripSchema } from './Trip';
export * from './WrapperCollection';
export { WrapperCollectionSchema } from './WrapperCollection';
